#version: "3.9"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - n8n_network

  n8n:
    # Use your custom n8n image that includes Python and npm packages
    image: n8n-docker-python
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - EXECUTIONS_MODE=regular
      - N8N_LOG_LEVEL=info
      - N8N_INSTALL_CUSTOM_NODES=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
#      - /home/node/logs:/home/node/logs
#      - n8n_downloads:/files/downloads
#      - ./python_scripts:/data/py_scripts
#      - ./requirements.txt:/data/requirements.txt
    networks:
      - n8n_network

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true
  n8n_downloads:
    external: true

networks:
  n8n_network:
    driver: bridge
